weather/weather/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

weather/weatherapp/urls.py
from django.conf.urls import *

from . import views


urlpatterns = [
    # Examples:
    # url(r'^$', weather.views.home, name='home'),
   
    url(r'^$', views.index, name='index'),
    url(r'^weather/$', views.get_weather, name='get weather'),
    url(r'^about/$', views.about, name='about'),

    #url(r'^$', HomePageView.as_view(), name='index'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

weather/weatherapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

weather/weatherapp/forms.py
from django import forms

class NameForm(forms.Form):
    #location type: true for latitude longitude, false for city name
    locType = forms.BooleanField(required=False, widget=forms.HiddenInput)
    
    #field to hold the user provided location
    userLoc = forms.CharField(label='Your name', max_length=100)

weather/weatherapp/views.py
import textwrap
import urls
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.base import View
from django.template import loader
from .forms import NameForm
from .apiCall import getWeather
from json2html import *

def index(request):
    form = NameForm()
    return render(request, 'weather.html', {'form': form})
    
def get_weather(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            st=getWeather(form.cleaned_data['userLoc'],form.cleaned_data['locType'])

            content = {'location': st['name'], 'temp': st['main']['temp'],'tempmax': st['main']['temp_max'],
                       'tempmin': st['main']['temp_min'],'description': st['weather'][0]['description'],
                       'wind': st['wind']['speed'] }

            # redirect to a new URL:json2html.convert(json=st)
            return render(request, 'weather.html', {'form': form,'content': content})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'weather.html', {'form': form})

def about(request):
    return render(request, 'about.html')

weather/weatherapp/templates/about.html
{% extends "base.html" %}


{% block header %}
{% load staticfiles %}
 <header class="intro-header" style="background-image: url('{% static "img/about-bg.jpg" %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>I am Siva Ramakrishnan. I built this website on Python 2.7, Django and Apache.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

    <hr />
{% endblock %}

weather/weatherapp/templates/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
    {% load staticfiles %}
    <link href="{% static "weatherapp/bootstrap/css/bootstrap.css" %}" rel="stylesheet" />
    <link href="{% static "weatherapp/bootstrap/css/clean-blog.css" %}" rel="stylesheet" />
    <script src="{% static "weatherapp/bootstrap/js/bootstrap.js" %}"></script>
    <script src="{% static "weatherapp/app.js" %}"></script>

      <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>{% block title %}How's the Weather{% endblock %}</title>
</head>
<body>
     <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="index.html">How's the Weather</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/about">About</a>
                    </li>                    
                   
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div id="header">
        {% block header %}{% endblock %}
    </div>
   
     <div id="content">
        {% block content %}{% endblock %}
    </div>

     <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; theweather.zapto.org 2016</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

weather/weatherapp/templates/index.html
{% extends "base.html" %}
    
{% block content %}
   
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on July 8, 2014</p>
                </div>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; theweather.zapto.org 2016</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

weather/weatherapp/templates/weather.html
{% extends "base.html" %}

{% block header %}
 <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
{% load staticfiles %}
    <header class="intro-header" style="background-image: url('{% static "img/home-bg.jpg" %}')">
        <div class="container">
            <div class="row">
                <div >
                    <div class="site-heading">
                        <h1>Weather Forecast</h1>
                        <hr class="small">
                        <span class="subheading">Get the Weather Forecast</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}


{% block content %}
	<div class="container">
        <div class="row">
            <h2> Select one of below options : </h2>
        </div>
		<div class="row">
			 <div>
<div id="form-block" class="hidden">
<div class="btn-group" role="group" aria-label="group">
  <button type="button" id="btn-currentlocType" class="btn btn-primary">Get the Weather for your current location</button>
  <button type="button" id="btn-customlocType" class="btn btn-primary">Find the Weather for another location</button>
</div>
    <br />
<form id="weatherForm" action="/weather/" method="post" >
	{% csrf_token %}
	<div class="form-group">
	  <input  class="form-control" id="id_locType" name="locType" type="hidden" value="{{ form.locType.value |default_if_none:''}}">
		<input class="form-control" placeholder="Search" 
			   id="id_userLoc" maxlength="100" name="userLoc" type="text" 
			   required=""
			   value="{{ form.userLoc.value |default_if_none:''}}">
		</div>
		<button type="submit" class="btn btn-default btn-submit">Submit</button>
</form>
    <hr />

 <div id="geolocTypeMessage" class="hidden">Geolocation is not supported for this Browser/OS.</div>
    <br />
  
    {% if content %}
    <table class="table table-striped table-bordered">
       <tbody>
        <tr>
          <th scope="row">Location:</th>
          <td>{{ content.location }}</td>
        </tr>    
        <tr>
          <th scope="row">Description:</th>
          <td>{{ content.description }}</td>
        </tr>  
        <tr>
        <tr>
          <th scope="row">Temperature(℉):</th>
          <td>{{ content.temp }}</td>
        </tr>  
        <tr>
          <th scope="row">Maximum Temperature(℉):</th>
          <td>{{ content.tempmax }}</td>
        </tr>    
        <tr>
          <th scope="row">Minimum Temperature(℉):</th>
          <td>{{ content.tempmin }}</td>
        </tr>    
        <tr>
          <th scope="row">Wind Speed(mps):</th>
          <td>{{ content.wind }}</td>
        </tr>      
      </tbody>
    </table>
    {% endif %}
</div>

</div>
			</div>
		</div>

{% endblock %}